# *Data Cleaning*

* Importing the data set(CSV)
* Observe the data set
    * Identify the rows/columns and their relation 
    * Identify the index column (Primary key column)
    * Check if there are any duplicate columns
    * Which rows to be skipped
* Assign the index column (To avoid creation of new index column )
* Skip irrelevant rows (To avoid display of index row)
* Drop dupliacte / irrelevant columns (For faster Operations)

# *Data Retrieval*

* Retrive Index columns -- df.index
* Columns names    -- df.columns
* second columns   -- df[Column_name]  # output in series format  
* any columns     -- df[[Column_name]] # output in DataFrame
* First Row      -- df.head(1)
* Access single row -- df.iloc[index]
* Access single cell

In [50]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='№':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG
Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,ALG
Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,ARG
Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,ARM
Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,ANZ

In [169]:
df["Gold"] # getting
df["Gold"][4]  # getting row, column  # returns the gold medals won by the fifth country(row,column)
df[:1]    # returns 0th row with columns name
df.index[1] # returns the second country name
df.loc["Afghanistan"]
df.iloc[4][1]  # return 3rd row 1st column ()
df["Gold"][4]  # return gold medal column,3rd row
df.loc["India","Combined total"]  # df.loc["India","Combined total"] -- return total medals won by india
df.columns
df["Combined total"]
#df.loc["India"][-1]
df.loc["United States"]
df.index[0]
df.index[-1]
df["# Games"]
df["# Summer"][9] # return total no. of games participated by 10th country
df["Combined total"][-1] # returns total medals of last country
df.loc["United States","Gold.2"] # return total number of gold medals in united states
abs(df.loc["United States","Gold"]-df.loc["China","Gold"])
df["Gold.1"].max()
#df["Gold.1"].argmax()  
df["Gold"].sum()
sum(df["Gold"])
df[df["Gold"] == df["Gold"].max()].index[0]
df[df["Total"] == df["Total"].max()]
df[df["Combined total"] == df["Combined total"].max()].index[0]
df1=df[(df["Gold"]>0) & (df["Gold.1"]>0)]
df1
(abs(df1["Gold"]-df1["Gold.1"])/df1["Gold.2"]).idxmax()

'Bulgaria'

In [49]:
import pandas as pd 
df = pd.read_csv("olympics.csv",index_col=0,skiprows=1)
df.index
df.columns
df.index[0]
df["Total"]# axis is used in function 
df[["Total.1"]] # the output  in DF
df.head(1)
df.iloc[0]
df.index
#df.loc['Yugoslavia (YUG) [YUG]']
df.index[0]
df.columns

Index(['№ Summer', '01 !', '02 !', '03 !', 'Total', '№ Winter', '01 !.1',
       '02 !.1', '03 !.1', 'Total.1', '№ Games', '01 !.2', '02 !.2', '03 !.2',
       'Combined total'],
      dtype='object')

In [209]:
# Calculate second most popular state using censun

dff=pd.read_csv("census.csv")
dff=dff.set_index("STNAME")
dff=dff.sort_values(by= "CENSUS2010POP")
dff
dff[["CENSUS2010POP"]].index[0]

dff["STNAME"].value_counts()

KeyError: 'STNAME'

In [ ]:
dff[""]

# Pandas Topics
 * Convert Dict to DataFrames -- pd.DtaFrame({...})
 * skiprows  -- skiprows = value
 * Get top rows from df -- df.head(10)
 * Get bottom rows from df -- df.tail(10)
 * Get specified rows from df -- df.iloc[index]  or -- df.iloc[[index_val1,index_val2]]
 * Get specified row and columns -- df.loc[[Row_names],[Column_names]]
 * Get Max of column -- df[column_name].max()
 * Get attributes of Column -- df[column_name].min() df[column_name].mean()  df[column_name].median() 
 * set row as index by using --  usecol= value
 * Get Columns -- df.columns
 * Get columns slicing -- df.columns[:]
 * rename Column names  -- pd.rename(columns= { "old column name" = "new Column name"})
 * Get specified Columns in DataFrame -- df[[ column_name1,Column_name2]]
 * Get column in Series -- pd.Series(df[column_name])
 * To remove columns -- pd.drop(colum_name,axis=1,inplace=True)
 * To Convert Columns as Index -- pd.set_index(column_name)
 * To reset Index into Columns -- pd.reset_index()
 * To get index of specified value in a column -- df[column_name].idxmax() or -- df[Column_name].argmax()
 * Replace anything -- df.replace(old_val,new_val)
 * Merge of 2 files  -- pd.merge(file1,file2,how=inner/outer,right_on=Column_name,left_on=Column_name)

In [14]:
import numpy as np

a = np.arange(10) # to create numpy array with 10 elements 

print(np.roll(a,4) ) # to create numpy array and shifts circularly np.roll(itarable,no. of positions)
np.roll(a,-4)

[6 7 8 9 0 1 2 3 4 5]

array([4, 5, 6, 7, 8, 9, 0, 1, 2, 3])

In [20]:
import pandas as pd
dir(pd)

['Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Float64Index',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int64Index',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NaT',
 'Panel',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseArray',
 'SparseDataFrame',
 'SparseDtype',
 'SparseSeries',
 'TimeGrouper',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt64Index',
 'UInt8Dtype',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_hashtable',
 '_lib',
 '_libs',
 '_np_version_under1p13',
 '_np_version_under1p14',
 '_np_version_under1p15',
 '_np_version_under1p16',
 '_np_version_under1p17',
 '_tslib',
 '_version',
 'api',
 'array',
 'arrays',
 'bdate_range',
 'compat',
 'concat',
 'core',
 'crosstab',
 'cut',
 'date_range',
 'datetime',
 'describe_option',
 'errors',
 'eval',
 'factorize',
 'get_dummies',
 'get_option',
 'infer_freq',
 'interval_range',
 'io',
 'isna',
 'isnull',
 'lreshape',
 'melt',
 'merge',
 'merge_asof',
 'merge_ordered',
 'notna',
 'notnull',
 'np',
 'offsets',
 'option_context',
 'options',
 'pandas',
 'period_range',
 'pivot',
 'pivot_table',
 'plotting',
 'qcut',
 'read_clipboard',
 'read_csv',
 'read_excel',
 'read_feather',
 'read_fwf',
 'read_gbq',
 'read_hdf',
 'read_html',
 'read_json',
 'read_msgpack',
 'read_parquet',
 'read_pickle',
 'read_sas',
 'read_sql',
 'read_sql_query',
 'read_sql_table',
 'read_stata',
 'read_table',
 'reset_option',
 'set_eng_float_format',
 'set_option',
 'show_versions',
 'test',
 'testing',
 'timedelta_range',
 'to_datetime',
 'to_msgpack',
 'to_numeric',
 'to_pickle',
 'to_timedelta',
 'tseries',
 'unique',
 'util',
 'value_counts',
 'wide_to_long']

In [137]:
import pandas as pd

df= pd.read_csv("world_bank2.csv")
df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Last Updated Date,2016-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Country Name,Country Code,Indicator Name,Indicator Code,1.960000e+03,1.961000e+03,1.962000e+03,1.963000e+03,1.964000e+03,1.965000e+03,...,2.006000e+03,2.007000e+03,2.008000e+03,2.009000e+03,2.010000e+03,2.011000e+03,2.012000e+03,2.013000e+03,2.014000e+03,2.015000e+03
4,Aruba,ABW,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
5,Andorra,AND,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
6,Afghanistan,AFG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
7,Angola,AGO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,9.012096e+10,9.626143e+10,1.008863e+11,1.039106e+11
8,Albania,ALB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10
9,Arab World,ARB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.763824e+12,1.863481e+12,1.980983e+12,2.011001e+12,2.103825e+12,2.173896e+12,2.318267e+12,2.385580e+12,2.436659e+12,2.509068e+12
10,United Arab Emirates,ARE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.789489e+11,2.878318e+11,2.970189e+11,2.814464e+11,2.860493e+11,3.009462e+11,3.216922e+11,3.355937e+11,3.509313e+11,3.621003e+11
11,Argentina,ARG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.206739e+11,1.272239e+11,1.261399e+11,1.194442e+11,1.315442e+11,1.454477e+11,...,3.788140e+11,4.089887e+11,4.215649e+11,4.217758e+11,4.616402e+11,5.003555e+11,5.043671e+11,5.189199e+11,5.212737e+11,NaN
12,Armenia,ARM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.679746e+09,9.873142e+09,1.055439e+10,9.060944e+09,9.260285e+09,9.695518e+09,1.039360e+10,1.073658e+10,1.111236e+10,1.144574e+10
13,American Samoa,ASM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Antigua and Barbuda,ATG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.268714e+09,1.389229e+09,1.390217e+09,1.222890e+09,1.135539e+09,1.115174e+09,1.159999e+09,1.155982e+09,1.211723e+09,1.256122e+09
15,Australia,AUS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.983395e+11,2.032502e+11,2.059485e+11,2.187430e+11,2.340028e+11,2.479962e+11,...,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
16,Austria,AUT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,9.223779e+10,9.734590e+10,9.992428e+10,1.040594e+11,1.104324e+11,1.142756e+11,...,3.782096e+11,3.919065e+11,3.979703e+11,3.828512e+11,3.902351e+11,4.011929e+11,4.042312e+11,4.055298e+11,4.069632e+11,4.104717e+11
17,Azerbaijan,AZE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.329047e+10,4.162940e+10,4.611390e+10,5.045352e+10,5.290270e+10,5.293758e+10,5.410221e+10,5.723834e+10,5.838310e+10,5.902532e+10
18,Burundi,BDI,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,5.966083e+08,5.145977e+08,5.612365e+08,5.844459e+08,6.211084e+08,6.457492e+08,...,1.714698e+09,1.796761e+09,1.887463e+09,1.952928e+09,2.026864e+09,2.111823e+09,2.196705e+09,2.297623e+09,2.404713e+09,2.343733e+09
19,Belgium,BEL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.205638e+11,1.265660e+11,1.331626e+11,1.389573e+11,1.486241e+11,1.539161e+11,...,4.626081e+11,4.783251e+11,4.818987e+11,4.708879e+11,4.835775e+11,4.922666e+11,4.930476e+11,4.930627e+11,4.994502e+11,5.063123e+11
20,Benin,BEN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.265426e+09,1.305177e+09,1.260456e+09,1.320076e+09,1.407871e+09,1.482402e+09,...,6.000596e+09,6.359822e+09,6.671034e+09,6.825750e+09,6.970241e+09,7.176752e+09,7.509970e+09,8.026581e+09,8.551638e+09,8.999782e+09
21,Burkina Faso,BFA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.120812e+09,1.166137e+09,1.237607e+09,1.221914e+09,1.249808e+09,1.296857e+09,...,7.094394e+09,7.495583e+09,8.042348e+09,8.280563e+09,8.979967e+09,9.565619e+09,1.018286e+10,1.055446e+10,1.098168e+10,1.141871e+10
22,Bangladesh,BGD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.786255e+10,1.894469e+10,1.997775e+10,1.988667e+10,2.206481e+10,2.241923e+10,...,9.158885e+10,9.805377e+10,1.039505e+11,1.091950e+11,1.152791e+11,1.227312e+11,1.307350e+11,1.385969e+11,1.469974e+11,1.566295e+11
23,Bulgaria,BGR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.580943e+10,4.932546e+10,5.211087e+10,4.991194e+10,4.993917e+10,5.073019e+10,5.085046e+10,5.150230e+10,5.230059e+10,5.385242e+10
24,Bahrain,BHR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.088961e+10,2.262186e+10,2.403463e+10,2.464505e+10,2.571327e+10,2.625330e+10,2.719545e+10,2.866752e+10,2.995210e+10,3.082866e+10
25,"Bahamas, The",BHS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.521892e+09,1.684234e+09,1.860270e+09,2.056046e+09,2.271963e+09,2.508828e+09,...,8.203865e+09,8.322536e+09,8.129126e+09,7.789714e+09,7.909580e+09,7.958058e+09,8.134513e+09,8.136305e+09,8.219522e+09,8.319840e+09
26,Bosnia and Herzegovina,BIH,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.572365e+10,1.662442e+10,1.753569e+10,1.703244e+10,1.716312e+10,1.731900e+10,1.715738e+10,1.756816e+10,1.775823e+10,1.831896e+10
27,Belarus,BLR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.274098e+10,4.641670e+10,5.115121e+10,5.125351e+10,5.522093e+10,5.828222e+10,5.929132e+10,5.992787e+10,6.096048e+10,5.859052e+10
28,Belize,BLZ,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,9.865406e+07,1.034805e+08,1.085434e+08,1.139233e+08,1.196193e+08,1.255172e+08,...,1.285312e+09,1.299522e+09,1.341485e+09,1.352206e+09,1.397113e+09,1.426484e+09,1.479846e+09,1.499280e+09,1.560479e+09,1.590417e+09
29,Bermuda,BMU,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.236025e+09,1.293871e+09,1.351707e+09,1.366170e+09,1.517951e+09,1.590206e+09,...,5.932559e+09,6.101393e+09,6.194616e+09,5.867282e+09,5.744414e+09,5.552580e+09,5.284138e+09,5.151445e+09,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,Middle East & North Africa (IDA & IBRD countries),TMN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,1.995513e+11,...,1.128451e+12,1.200513e+12,1.246733e+12,1.284551e+12,1.354033e+12,1.344512e+12,1.381807e+12,1.394728e+12,1.416758e+12,NaN
239,Timor-Leste,TLS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.940000e+08,6.620000e+08,7.560000e+08,8.540000e+08,9.340000e+08,1.023000e+09,1.088000e+09,1.118000e+09,1.179490e+09,1.229630e+09
240,Tonga,TON,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.591646e+08,3.427468e+08,3.511655e+08,3.550268e+08,3.698161e+08,3.772832e+08,3.793467e+08,3.691972e+08,3.771126e+08,NaN
241,South Asia (IDA & IBRD),TSA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.840484e+11,1.916061e+11,1.979559e+11,2.086032e+11,2.246484e+11,2.223897e+11,...,1.588121e+12,1.716564e+12,1.783227e+12,1.919371e+12,2.093719e+12,2.226077e+12,2.351842e+12,2.499225e+12,2.670483e+12,2.862660e+12
242,Sub-Saharan Africa (IDA & IBRD countries),TSS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.448081e+11,2.484306e+11,2.629561e+11,2.795305e+11,2.945791e+11,3.123708e+11,...,1.107337e+12,1.185713e+12,1.248779e+12,1.284295e+12,1.355385e+12,1.413707e+12,1.465242e+12,1.534734e+12,1.605815e+12,1.653644e+12
243,Trinidad and Tobago,TTO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.198187e+09,4.787490e+09,4.918785e+09,5.194463e+09,5.590826e+09,5.629618e+09,...,2.033516e+10,2.130193e+10,2.202416e+10,2.105717e+10,2.103761e+10,2.103908e+10,2.132649e+10,2.169752e+10,2.187468e+10,2.209480e+10
244,Tunisia,TUN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,5.059839e+09,...,3.712967e+10,3.962093e+10,4.129998e+10,4.255692e+10,4.405093e+10,4.300079e+10,4.459182e+10,4.561743e+10,4.666663e+10,4.703997e+10
245,Turkey,TUR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,8.362456e+10,8.459132e+10,8.930427e+10,9.740087e+10,1.027180e+11,1.056183e+11,...,6.680034e+11,6.991896e+11,7.037962e+11,6.698319e+11,7.311681e+11,7.953116e+11,8.122315e+11,8.462844e+11,8.718432e+11,9.065849e+11
246,Tuvalu,TUV,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.980999e+07,3.170309e+07,3.423404e+07,3.271649e+07,3.182352e+07,3.451366e+07,3.457388e+07,3.502271e+07,3.571892e+07,NaN
247,Tanzania,TZA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.447280e+10,2.654427e+10,2.802189e+10,2.953012e+10,3.140791e+10,3.389055e+10,3.563287e+10,3.822090e+10,4.088304e+10,4.373172e+10
248,Uganda,UGA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.518174e+10,1.645889e+10,1.789225e+10,1.918963e+10,2.018180e+10,2.213403e+10,2.311042e+10,2.386630e+10,2.501553e+10,2.627705e+10
249,Ukraine,UKR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.392103e+11,1.502079e+11,1.536627e+11,1.309206e+11,1.364193e+11,1.435131e+11,1.438001e+11,1.438001e+11,1.343093e+11,1.210127e+11
250,Upper middle income,UMC,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.456839e+12,1.477022e+12,1.541565e+12,1.631063e+12,1.764693e+12,1.884705e+12,...,1.209926e+13,1.319424e+13,1.398552e+13,1.423007e+13,1.530029e+13,1.623576e+13,1.706156e+13,1.786328e+13,1.856972e+13,1.912141e+13
251,Uruguay,URY,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.389822e+10,1.424471e+10,1.402042e+10,1.404432e+10,1.438707e+10,1.453751e+10,...,3.139363e+10,3.344725e+10,3.584747e+10,3.736865e+10,4.028468e+10,4.236423e+10,4.386315e+10,4.589732e+10,4.738384e+10,4.784927e+10
252,United States,USA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.078071e+12,3.148867e+12,3.340948e+12,3.487949e+12,3.690250e+12,3.926426e+12,...,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
253,Uzbekistan,UZB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.798925e+10,3.076611e+10,3.353506e+10,3.625140e+10,3.933277e+10,4.259739e+10,4.609038e+10,4.977761e+10,5.380959e+10,5.811436e+10
254,St. Vincent and the Grenadines,VCT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.418778e+08,1.483010e+08,1.537796e+08,1.441448e+08,1.494345e+08,1.507569e+08,...,6.857344e+08,6.746459e+08,7.200629e+08,7.049483e+08,6.812260e+08,6.783400e+08,6.877044e+08,6.991892e+08,7.037801e+08,7.139983e+08
255,"Venezuela, RB",VEN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.015817e+11,1.048247e+11,1.137694e+11,1.182074e+11,1.313632e+11,1.368316e+11,...,3.606999e+11,3.922741e+11,4.129777e+11,3.997529e+11,3.938015e+11,4.102483e+11,4.333287e+11,4.391487e+11,4.220465e+11,3.979899e+11
256,British Virgin Islands,VGB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,Virgin Islands (U.S.),VIR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,Vietnam,VNM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.130761e+10,9.781739e+10,1.033556e+11,1.089346e+11,1.159317e+11,1.231662e+11,1.296292e+11,1.366576e+11,1.448347e+11,1.545086e+11
259,Vanuatu,VUT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.961693e+08,6.270251e+08,6.674589e+08,6.895706e+08,7.008043e+08,7.093767e+08,7.218245e+08,7.360383e+08,7.529991e+08,NaN
260,West Bank and Gaza,PSE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.016675e+09,7.878227e+09,7.201473e+09,8.709518e+09,8.913100e+09,9.611505e+09,1.100864e+10,1.053747e+10,1.042246e+10,1.171414e+10
261,World,WLD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.118678e+13,1.166806e+13,1.231357e+13,1.295118e+13,1.381212e+13,1.458038e+13,...,6.023536e+13,6.282865e+13,6.398692e+13,6.291271e+13,6.564782e+13,6.770244e+13,6.937886e+13,7.104232e+13,7.291072e+13,7.470901e+13
262,Samoa,WSM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.393881e+08,6.798143e+08,6.866743e+08,6.536571e+08,6.567891e+08,6.947420e+08,6.975356e+08,6.840462e+08,6.922284e+08,7.035448e+08
263,"Yemen, Rep.",YEM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.672565e+10,2.761787e+10,2.872656e+10,2.991436e+10,3.090675e+10,2.624342e+10,2.689160e+10,2.800914e+10,NaN,NaN
264,South Africa,ZAF,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,7.707081e+10,8.003449e+10,8.497844e+10,9.124438e+10,9.848904e+10,1.072507e+11,...,3.402852e+11,3.585261e+11,3.699668e+11,3.642764e+11,3.753494e+11,3.874074e+11,3.960071e+11,4.047682e+11,4.110369e+11,4.163117e+11
265,"Congo, Dem. Rep.",COD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.508024e+10,1.344383e+10,1.629401e+10,1.714358e+10,1.672524e+10,1.689205e+10,...,1.650894e+10,1.754232e+10,1.863448e+10,1.916651e+10,2.052329e+10,2.193213e+10,2.350200e+10,2.550050e+10,2.778776e+10,2.970961e+10
266,Zambia,ZMB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.592975e+09,4.655503e+09,4.539542e+09,4.688093e+09,5.260699e+09,6.136472e+09,...,1.440569e+10,1.560892e+10,1.682234e+10,1.837342e+10,2.026555e+10,2.140358e+10,2.302438e+10,2.420595e+10,2.542227e+10,2.624127e+10
267,Zimbabwe,ZWE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.338344e+09,3.549199e+09,3.600111e+09,3.824915e+09,3.782605e+09,3.968352e+09,...,1.006276e+10,9.695130e+09,7.982103e+09,8.459783e+09,9.422161e+09,1.054391e+10,1.165789e+10,1.218064e+10,1.264939e+10,1.278517e+10

In [138]:
df=df.replace("NaN","")
df

,Data Source,World Development Indicators,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Last Updated Date,2016-07-22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Country Name,Country Code,Indicator Name,Indicator Code,1.960000e+03,1.961000e+03,1.962000e+03,1.963000e+03,1.964000e+03,1.965000e+03,...,2.006000e+03,2.007000e+03,2.008000e+03,2.009000e+03,2.010000e+03,2.011000e+03,2.012000e+03,2.013000e+03,2.014000e+03,2.015000e+03
4,Aruba,ABW,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
5,Andorra,AND,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
6,Afghanistan,AFG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
7,Angola,AGO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,9.012096e+10,9.626143e+10,1.008863e+11,1.039106e+11
8,Albania,ALB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.771760e+09,1.034829e+10,1.112752e+10,1.150029e+10,1.192695e+10,1.223109e+10,1.240477e+10,1.254247e+10,1.279331e+10,1.312082e+10
9,Arab World,ARB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.763824e+12,1.863481e+12,1.980983e+12,2.011001e+12,2.103825e+12,2.173896e+12,2.318267e+12,2.385580e+12,2.436659e+12,2.509068e+12
10,United Arab Emirates,ARE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.789489e+11,2.878318e+11,2.970189e+11,2.814464e+11,2.860493e+11,3.009462e+11,3.216922e+11,3.355937e+11,3.509313e+11,3.621003e+11
11,Argentina,ARG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.206739e+11,1.272239e+11,1.261399e+11,1.194442e+11,1.315442e+11,1.454477e+11,...,3.788140e+11,4.089887e+11,4.215649e+11,4.217758e+11,4.616402e+11,5.003555e+11,5.043671e+11,5.189199e+11,5.212737e+11,NaN
12,Armenia,ARM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.679746e+09,9.873142e+09,1.055439e+10,9.060944e+09,9.260285e+09,9.695518e+09,1.039360e+10,1.073658e+10,1.111236e+10,1.144574e+10
13,American Samoa,ASM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Antigua and Barbuda,ATG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.268714e+09,1.389229e+09,1.390217e+09,1.222890e+09,1.135539e+09,1.115174e+09,1.159999e+09,1.155982e+09,1.211723e+09,1.256122e+09
15,Australia,AUS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.983395e+11,2.032502e+11,2.059485e+11,2.187430e+11,2.340028e+11,2.479962e+11,...,1.021939e+12,1.060340e+12,1.099644e+12,1.119654e+12,1.142251e+12,1.169431e+12,1.211913e+12,1.241484e+12,1.272520e+12,1.301251e+12
16,Austria,AUT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,9.223779e+10,9.734590e+10,9.992428e+10,1.040594e+11,1.104324e+11,1.142756e+11,...,3.782096e+11,3.919065e+11,3.979703e+11,3.828512e+11,3.902351e+11,4.011929e+11,4.042312e+11,4.055298e+11,4.069632e+11,4.104717e+11
17,Azerbaijan,AZE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.329047e+10,4.162940e+10,4.611390e+10,5.045352e+10,5.290270e+10,5.293758e+10,5.410221e+10,5.723834e+10,5.838310e+10,5.902532e+10
18,Burundi,BDI,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,5.966083e+08,5.145977e+08,5.612365e+08,5.844459e+08,6.211084e+08,6.457492e+08,...,1.714698e+09,1.796761e+09,1.887463e+09,1.952928e+09,2.026864e+09,2.111823e+09,2.196705e+09,2.297623e+09,2.404713e+09,2.343733e+09
19,Belgium,BEL,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.205638e+11,1.265660e+11,1.331626e+11,1.389573e+11,1.486241e+11,1.539161e+11,...,4.626081e+11,4.783251e+11,4.818987e+11,4.708879e+11,4.835775e+11,4.922666e+11,4.930476e+11,4.930627e+11,4.994502e+11,5.063123e+11
20,Benin,BEN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.265426e+09,1.305177e+09,1.260456e+09,1.320076e+09,1.407871e+09,1.482402e+09,...,6.000596e+09,6.359822e+09,6.671034e+09,6.825750e+09,6.970241e+09,7.176752e+09,7.509970e+09,8.026581e+09,8.551638e+09,8.999782e+09
21,Burkina Faso,BFA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.120812e+09,1.166137e+09,1.237607e+09,1.221914e+09,1.249808e+09,1.296857e+09,...,7.094394e+09,7.495583e+09,8.042348e+09,8.280563e+09,8.979967e+09,9.565619e+09,1.018286e+10,1.055446e+10,1.098168e+10,1.141871e+10
22,Bangladesh,BGD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.786255e+10,1.894469e+10,1.997775e+10,1.988667e+10,2.206481e+10,2.241923e+10,...,9.158885e+10,9.805377e+10,1.039505e+11,1.091950e+11,1.152791e+11,1.227312e+11,1.307350e+11,1.385969e+11,1.469974e+11,1.566295e+11
23,Bulgaria,BGR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.580943e+10,4.932546e+10,5.211087e+10,4.991194e+10,4.993917e+10,5.073019e+10,5.085046e+10,5.150230e+10,5.230059e+10,5.385242e+10
24,Bahrain,BHR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.088961e+10,2.262186e+10,2.403463e+10,2.464505e+10,2.571327e+10,2.625330e+10,2.719545e+10,2.866752e+10,2.995210e+10,3.082866e+10
25,"Bahamas, The",BHS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.521892e+09,1.684234e+09,1.860270e+09,2.056046e+09,2.271963e+09,2.508828e+09,...,8.203865e+09,8.322536e+09,8.129126e+09,7.789714e+09,7.909580e+09,7.958058e+09,8.134513e+09,8.136305e+09,8.219522e+09,8.319840e+09
26,Bosnia and Herzegovina,BIH,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.572365e+10,1.662442e+10,1.753569e+10,1.703244e+10,1.716312e+10,1.731900e+10,1.715738e+10,1.756816e+10,1.775823e+10,1.831896e+10
27,Belarus,BLR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.274098e+10,4.641670e+10,5.115121e+10,5.125351e+10,5.522093e+10,5.828222e+10,5.929132e+10,5.992787e+10,6.096048e+10,5.859052e+10
28,Belize,BLZ,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,9.865406e+07,1.034805e+08,1.085434e+08,1.139233e+08,1.196193e+08,1.255172e+08,...,1.285312e+09,1.299522e+09,1.341485e+09,1.352206e+09,1.397113e+09,1.426484e+09,1.479846e+09,1.499280e+09,1.560479e+09,1.590417e+09
29,Bermuda,BMU,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.236025e+09,1.293871e+09,1.351707e+09,1.366170e+09,1.517951e+09,1.590206e+09,...,5.932559e+09,6.101393e+09,6.194616e+09,5.867282e+09,5.744414e+09,5.552580e+09,5.284138e+09,5.151445e+09,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,Middle East & North Africa (IDA & IBRD countries),TMN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,1.995513e+11,...,1.128451e+12,1.200513e+12,1.246733e+12,1.284551e+12,1.354033e+12,1.344512e+12,1.381807e+12,1.394728e+12,1.416758e+12,NaN
239,Timor-Leste,TLS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.940000e+08,6.620000e+08,7.560000e+08,8.540000e+08,9.340000e+08,1.023000e+09,1.088000e+09,1.118000e+09,1.179490e+09,1.229630e+09
240,Tonga,TON,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.591646e+08,3.427468e+08,3.511655e+08,3.550268e+08,3.698161e+08,3.772832e+08,3.793467e+08,3.691972e+08,3.771126e+08,NaN
241,South Asia (IDA & IBRD),TSA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.840484e+11,1.916061e+11,1.979559e+11,2.086032e+11,2.246484e+11,2.223897e+11,...,1.588121e+12,1.716564e+12,1.783227e+12,1.919371e+12,2.093719e+12,2.226077e+12,2.351842e+12,2.499225e+12,2.670483e+12,2.862660e+12
242,Sub-Saharan Africa (IDA & IBRD countries),TSS,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,2.448081e+11,2.484306e+11,2.629561e+11,2.795305e+11,2.945791e+11,3.123708e+11,...,1.107337e+12,1.185713e+12,1.248779e+12,1.284295e+12,1.355385e+12,1.413707e+12,1.465242e+12,1.534734e+12,1.605815e+12,1.653644e+12
243,Trinidad and Tobago,TTO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.198187e+09,4.787490e+09,4.918785e+09,5.194463e+09,5.590826e+09,5.629618e+09,...,2.033516e+10,2.130193e+10,2.202416e+10,2.105717e+10,2.103761e+10,2.103908e+10,2.132649e+10,2.169752e+10,2.187468e+10,2.209480e+10
244,Tunisia,TUN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,5.059839e+09,...,3.712967e+10,3.962093e+10,4.129998e+10,4.255692e+10,4.405093e+10,4.300079e+10,4.459182e+10,4.561743e+10,4.666663e+10,4.703997e+10
245,Turkey,TUR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,8.362456e+10,8.459132e+10,8.930427e+10,9.740087e+10,1.027180e+11,1.056183e+11,...,6.680034e+11,6.991896e+11,7.037962e+11,6.698319e+11,7.311681e+11,7.953116e+11,8.122315e+11,8.462844e+11,8.718432e+11,9.065849e+11
246,Tuvalu,TUV,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.980999e+07,3.170309e+07,3.423404e+07,3.271649e+07,3.182352e+07,3.451366e+07,3.457388e+07,3.502271e+07,3.571892e+07,NaN
247,Tanzania,TZA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.447280e+10,2.654427e+10,2.802189e+10,2.953012e+10,3.140791e+10,3.389055e+10,3.563287e+10,3.822090e+10,4.088304e+10,4.373172e+10
248,Uganda,UGA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.518174e+10,1.645889e+10,1.789225e+10,1.918963e+10,2.018180e+10,2.213403e+10,2.311042e+10,2.386630e+10,2.501553e+10,2.627705e+10
249,Ukraine,UKR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.392103e+11,1.502079e+11,1.536627e+11,1.309206e+11,1.364193e+11,1.435131e+11,1.438001e+11,1.438001e+11,1.343093e+11,1.210127e+11
250,Upper middle income,UMC,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.456839e+12,1.477022e+12,1.541565e+12,1.631063e+12,1.764693e+12,1.884705e+12,...,1.209926e+13,1.319424e+13,1.398552e+13,1.423007e+13,1.530029e+13,1.623576e+13,1.706156e+13,1.786328e+13,1.856972e+13,1.912141e+13
251,Uruguay,URY,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.389822e+10,1.424471e+10,1.402042e+10,1.404432e+10,1.438707e+10,1.453751e+10,...,3.139363e+10,3.344725e+10,3.584747e+10,3.736865e+10,4.028468e+10,4.236423e+10,4.386315e+10,4.589732e+10,4.738384e+10,4.784927e+10
252,United States,USA,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.078071e+12,3.148867e+12,3.340948e+12,3.487949e+12,3.690250e+12,3.926426e+12,...,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13
253,Uzbekistan,UZB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.798925e+10,3.076611e+10,3.353506e+10,3.625140e+10,3.933277e+10,4.259739e+10,4.609038e+10,4.977761e+10,5.380959e+10,5.811436e+10
254,St. Vincent and the Grenadines,VCT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.418778e+08,1.483010e+08,1.537796e+08,1.441448e+08,1.494345e+08,1.507569e+08,...,6.857344e+08,6.746459e+08,7.200629e+08,7.049483e+08,6.812260e+08,6.783400e+08,6.877044e+08,6.991892e+08,7.037801e+08,7.139983e+08
255,"Venezuela, RB",VEN,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.015817e+11,1.048247e+11,1.137694e+11,1.182074e+11,1.313632e+11,1.368316e+11,...,3.606999e+11,3.922741e+11,4.129777e+11,3.997529e+11,3.938015e+11,4.102483e+11,4.333287e+11,4.391487e+11,4.220465e+11,3.979899e+11
256,British Virgin Islands,VGB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
257,Virgin Islands (U.S.),VIR,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,Vietnam,VNM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,9.130761e+10,9.781739e+10,1.033556e+11,1.089346e+11,1.159317e+11,1.231662e+11,1.296292e+11,1.366576e+11,1.448347e+11,1.545086e+11
259,Vanuatu,VUT,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.961693e+08,6.270251e+08,6.674589e+08,6.895706e+08,7.008043e+08,7.093767e+08,7.218245e+08,7.360383e+08,7.529991e+08,NaN
260,West Bank and Gaza,PSE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,8.016675e+09,7.878227e+09,7.201473e+09,8.709518e+09,8.913100e+09,9.611505e+09,1.100864e+10,1.053747e+10,1.042246e+10,1.171414e+10
261,World,WLD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.118678e+13,1.166806e+13,1.231357e+13,1.295118e+13,1.381212e+13,1.458038e+13,...,6.023536e+13,6.282865e+13,6.398692e+13,6.291271e+13,6.564782e+13,6.770244e+13,6.937886e+13,7.104232e+13,7.291072e+13,7.470901e+13
262,Samoa,WSM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,6.393881e+08,6.798143e+08,6.866743e+08,6.536571e+08,6.567891e+08,6.947420e+08,6.975356e+08,6.840462e+08,6.922284e+08,7.035448e+08
263,"Yemen, Rep.",YEM,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.672565e+10,2.761787e+10,2.872656e+10,2.991436e+10,3.090675e+10,2.624342e+10,2.689160e+10,2.800914e+10,NaN,NaN
264,South Africa,ZAF,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,7.707081e+10,8.003449e+10,8.497844e+10,9.124438e+10,9.848904e+10,1.072507e+11,...,3.402852e+11,3.585261e+11,3.699668e+11,3.642764e+11,3.753494e+11,3.874074e+11,3.960071e+11,4.047682e+11,4.110369e+11,4.163117e+11
265,"Congo, Dem. Rep.",COD,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,1.508024e+10,1.344383e+10,1.629401e+10,1.714358e+10,1.672524e+10,1.689205e+10,...,1.650894e+10,1.754232e+10,1.863448e+10,1.916651e+10,2.052329e+10,2.193213e+10,2.350200e+10,2.550050e+10,2.778776e+10,2.970961e+10
266,Zambia,ZMB,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,4.592975e+09,4.655503e+09,4.539542e+09,4.688093e+09,5.260699e+09,6.136472e+09,...,1.440569e+10,1.560892e+10,1.682234e+10,1.837342e+10,2.026555e+10,2.140358e+10,2.302438e+10,2.420595e+10,2.542227e+10,2.624127e+10
267,Zimbabwe,ZWE,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,3.338344e+09,3.549199e+09,3.600111e+09,3.824915e+09,3.782605e+09,3.968352e+09,...,1.006276e+10,9.695130e+09,7.982103e+09,8.459783e+09,9.422161e+09,1.054391e+10,1.165789e+10,1.218064e+10,1.264939e+10,1.278517e+10

In [179]:
df2=pd.read_csv("olympics.csv",index_col=0,skiprows=1)
df2.head(5)

,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !.1,02 !.1,03 !.1,Total.1,№ Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [37]:
df2[["01 !","02 !"]].head()

                         01 !  02 !
Afghanistan (AFG)           0     0
Algeria (ALG)               5     2
Argentina (ARG)            18    24
Armenia (ARM)               1     2
Australasia (ANZ) [ANZ]     3     4

In [85]:
df2[["01 !","02 !"]]

                                              01 !  02 !
Country
Afghanistan (AFG)                                0     0
Algeria (ALG)                                    5     2
Argentina (ARG)                                 18    24
Armenia (ARM)                                    1     2
Australasia (ANZ) [ANZ]                          3     4
Australia (AUS) [AUS] [Z]                      139   152
Austria (AUT)                                   18    33
Azerbaijan (AZE)                                 6     5
Bahamas (BAH)                                    5     2
Bahrain (BRN)                                    0     0
Barbados (BAR) [BAR]                             0     0
Belarus (BLR)                                   12    24
Belgium (BEL)                                   37    52
Bermuda (BER)                                    0     0
Bohemia (BOH) [BOH] [Z]                          0     1
Botswana (BOT)                                   0     1
Brazil (BRA)                                    23    30
British West Indies (BWI) [BWI]                  0     0
Bulgaria (BUL) [H]                              51    85
Burundi (BDI)                                    1     0
Cameroon (CMR)                                   3     1
Canada (CAN)                                    59    99
Chile (CHI) [I]                                  2     7
China (CHN) [CHN]                              201   146
Colombia (COL)                                   2     6
Costa Rica (CRC)                                 1     1
Ivory Coast (CIV) [CIV]                          0     1
Croatia (CRO)                                    6     7
Cuba (CUB) [Z]                                  72    67
Cyprus (CYP)                                     0     1
...                                            ...   ...
Sri Lanka (SRI) [SRI]                            0     2
Sudan (SUD)                                      0     1
Suriname (SUR) [E]                               1     0
Sweden (SWE) [Z]                               143   164
Switzerland (SUI)                               47    73
Syria (SYR)                                      1     1
Chinese Taipei (TPE) [TPE] [TPE2]                2     7
Tajikistan (TJK)                                 0     1
Tanzania (TAN) [TAN]                             0     2
Thailand (THA)                                   7     6
Togo (TOG)                                       0     0
Tonga (TGA)                                      0     1
Trinidad and Tobago (TRI) [TRI]                  2     5
Tunisia (TUN)                                    3     3
Turkey (TUR)                                    39    25
Uganda (UGA)                                     2     3
Ukraine (UKR)                                   33    27
United Arab Emirates (UAE)                       1     0
United States (USA) [P] [Q] [R] [Z]            976   757
Uruguay (URU)                                    2     2
Uzbekistan (UZB)                                 5     5
Venezuela (VEN)                                  2     2
Vietnam (VIE)                                    0     2
Virgin Islands (ISV)                             0     1
Yugoslavia (YUG) [YUG]                          26    29
Independent Olympic Participants (IOP) [IOP]     0     1
Zambia (ZAM) [ZAM]                               0     1
Zimbabwe (ZIM) [ZIM]                             3     4
Mixed team (ZZX) [ZZX]                           8     5
Totals                                        4809  4775

[147 rows x 2 columns]

In [48]:
df2[df2["01 !"]>250]

,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !.1,02 !.1,03 !.1,Total.1,№ Games,01 !.2,02 !.2,03 !.2,Combined total
Soviet Union (URS) [URS],9,395,319,296,1010,9,78,57,59,194,18,473,376,355,1204
United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [95]:
#df2=df2.reset_index()

#df2=df2.rename(columns={"index" : "Country" })
#df2=df2.set_index("Country")
#df2.drop("level_0",axis=1,inplace=True)
df2.iloc[[9,8]]

,level_0,index,Country,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !.1,02 !.1,03 !.1,Total.1,№ Games,01 !.2,02 !.2,03 !.2,Combined total
9,9,9,Bahrain (BRN),8,0,0,1,1,0,0,0,0,0,8,0,0,1,1
8,8,8,Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12

In [106]:
df2.loc[9,["Country","№ Games"]]

Country    Bahrain (BRN)
№ Games                8
Name: 9, dtype: object

In [112]:
df2["01 !"].max()

4809

In [113]:
df2["01 !"].min()

0

In [114]:
df2["01 !"].mean()

65.42857142857143

In [115]:
df2["01 !"].median()

3.0

In [117]:
df2["01 !"].idxmax()

146

In [118]:
df2.loc[146,"01 !"]

4809

In [140]:
df2.iloc[146]

№ Summer             27
01 !               4809
02 !               4775
03 !               5130
Total             14714
№ Winter             22
01 !.1              959
02 !.1              958
03 !.1              948
Total.1            2865
№ Games              49
01 !.2             5768
02 !.2             5733
03 !.2             6078
Combined total    17579
Name: Totals, dtype: int64

In [180]:
import numpy as np
df2=df2.replace(1,0)
df2

,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !.1,02 !.1,03 !.1,Total.1,№ Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,0,2,9,12,6,0,0,0,0,11,0,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
Bahrain (BRN),8,0,0,0,0,0,0,0,0,0,8,0,0,0,0
Barbados (BAR) [BAR],11,0,0,0,0,0,0,0,0,0,11,0,0,0,0
Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
Belgium (BEL),25,37,52,53,142,20,0,0,3,5,45,38,53,56,147
Bermuda (BER),17,0,0,0,0,7,0,0,0,0,24,0,0,0,0
Bohemia (BOH) [BOH] [Z],3,0,0,3,4,0,0,0,0,0,3,0,0,3,4
Botswana (BOT),9,0,0,0,0,0,0,0,0,0,9,0,0,0,0
Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
British West Indies (BWI) [BWI],0,0,0,2,2,0,0,0,0,0,0,0,0,2,2
Bulgaria (BUL) [H],19,51,85,78,214,19,0,2,3,6,38,52,87,81,220
Burundi (BDI),5,0,0,0,0,0,0,0,0,0,5,0,0,0,0
Cameroon (CMR),13,3,0,0,5,0,0,0,0,0,14,3,0,0,5
Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
Colombia (COL),18,2,6,11,19,0,0,0,0,0,19,2,6,11,19
Costa Rica (CRC),14,0,0,2,4,6,0,0,0,0,20,0,0,2,4
Ivory Coast (CIV) [CIV],12,0,0,0,0,0,0,0,0,0,12,0,0,0,0
Croatia (CRO),6,6,7,10,23,7,4,6,0,11,13,10,13,11,34
Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
Cyprus (CYP),9,0,0,0,0,10,0,0,0,0,19,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sri Lanka (SRI) [SRI],16,0,2,0,2,0,0,0,0,0,16,0,2,0,2
Sudan (SUD),11,0,0,0,0,0,0,0,0,0,11,0,0,0,0
Suriname (SUR) [E],11,0,0,0,2,0,0,0,0,0,11,0,0,0,2
Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
Syria (SYR),12,0,0,0,3,0,0,0,0,0,12,0,0,0,3
Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
Tajikistan (TJK),5,0,0,2,3,4,0,0,0,0,9,0,0,2,3
Tanzania (TAN) [TAN],12,0,2,0,2,0,0,0,0,0,12,0,2,0,2
Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
Togo (TOG),9,0,0,0,0,0,0,0,0,0,10,0,0,0,0
Tonga (TGA),8,0,0,0,0,0,0,0,0,0,9,0,0,0,0
Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
Ukraine (UKR),5,33,27,55,115,6,2,0,4,7,11,35,28,59,122
United Arab Emirates (UAE),8,0,0,0,0,0,0,0,0,0,8,0,0,0,0
United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
Uruguay (URU),20,2,2,6,10,0,0,0,0,0,21,2,2,6,10
Uzbekistan (UZB),5,5,5,10,20,6,0,0,0,0,11,6,5,10,21
Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
Virgin Islands (ISV),11,0,0,0,0,7,0,0,0,0,18,0,0,0,0
Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,0,4,30,26,32,29,87
Independent Olympic Participants (IOP) [IOP],0,0,0,2,3,0,0,0,0,0,0,0,0,2,3
Zambia (ZAM) [ZAM],12,0,0,0,2,0,0,0,0,0,12,0,0,0,2
Zimbabwe (ZIM) [ZIM],12,3,4,0,8,0,0,0,0,0,13,3,4,0,8
Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [181]:
df3=df2[:10]
df3

,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !.1,02 !.1,03 !.1,Total.1,№ Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,0,2,9,12,6,0,0,0,0,11,0,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
Bahrain (BRN),8,0,0,0,0,0,0,0,0,0,8,0,0,0,0

In [184]:
#df2=df2.drop(df.iloc[:10],axis=0,inplace=True)
df2

,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !.1,02 !.1,03 !.1,Total.1,№ Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,0,2,9,12,6,0,0,0,0,11,0,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12
Australia (AUS) [AUS] [Z],25,139,152,177,468,18,5,3,4,12,43,144,155,181,480
Austria (AUT),26,18,33,35,86,22,59,78,81,218,48,77,111,116,304
Azerbaijan (AZE),5,6,5,15,26,5,0,0,0,0,10,6,5,15,26
Bahamas (BAH),15,5,2,5,12,0,0,0,0,0,15,5,2,5,12
Bahrain (BRN),8,0,0,0,0,0,0,0,0,0,8,0,0,0,0
Barbados (BAR) [BAR],11,0,0,0,0,0,0,0,0,0,11,0,0,0,0
Belarus (BLR),5,12,24,39,75,6,6,4,5,15,11,18,28,44,90
Belgium (BEL),25,37,52,53,142,20,0,0,3,5,45,38,53,56,147
Bermuda (BER),17,0,0,0,0,7,0,0,0,0,24,0,0,0,0
Bohemia (BOH) [BOH] [Z],3,0,0,3,4,0,0,0,0,0,3,0,0,3,4
Botswana (BOT),9,0,0,0,0,0,0,0,0,0,9,0,0,0,0
Brazil (BRA),21,23,30,55,108,7,0,0,0,0,28,23,30,55,108
British West Indies (BWI) [BWI],0,0,0,2,2,0,0,0,0,0,0,0,0,2,2
Bulgaria (BUL) [H],19,51,85,78,214,19,0,2,3,6,38,52,87,81,220
Burundi (BDI),5,0,0,0,0,0,0,0,0,0,5,0,0,0,0
Cameroon (CMR),13,3,0,0,5,0,0,0,0,0,14,3,0,0,5
Canada (CAN),25,59,99,121,279,22,62,56,52,170,47,121,155,173,449
Chile (CHI) [I],22,2,7,4,13,16,0,0,0,0,38,2,7,4,13
China (CHN) [CHN],9,201,146,126,473,10,12,22,19,53,19,213,168,145,526
Colombia (COL),18,2,6,11,19,0,0,0,0,0,19,2,6,11,19
Costa Rica (CRC),14,0,0,2,4,6,0,0,0,0,20,0,0,2,4
Ivory Coast (CIV) [CIV],12,0,0,0,0,0,0,0,0,0,12,0,0,0,0
Croatia (CRO),6,6,7,10,23,7,4,6,0,11,13,10,13,11,34
Cuba (CUB) [Z],19,72,67,70,209,0,0,0,0,0,19,72,67,70,209
Cyprus (CYP),9,0,0,0,0,10,0,0,0,0,19,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sri Lanka (SRI) [SRI],16,0,2,0,2,0,0,0,0,0,16,0,2,0,2
Sudan (SUD),11,0,0,0,0,0,0,0,0,0,11,0,0,0,0
Suriname (SUR) [E],11,0,0,0,2,0,0,0,0,0,11,0,0,0,2
Sweden (SWE) [Z],26,143,164,176,483,22,50,40,54,144,48,193,204,230,627
Switzerland (SUI),27,47,73,65,185,22,50,40,48,138,49,97,113,113,323
Syria (SYR),12,0,0,0,3,0,0,0,0,0,12,0,0,0,3
Chinese Taipei (TPE) [TPE] [TPE2],13,2,7,12,21,11,0,0,0,0,24,2,7,12,21
Tajikistan (TJK),5,0,0,2,3,4,0,0,0,0,9,0,0,2,3
Tanzania (TAN) [TAN],12,0,2,0,2,0,0,0,0,0,12,0,2,0,2
Thailand (THA),15,7,6,11,24,3,0,0,0,0,18,7,6,11,24
Togo (TOG),9,0,0,0,0,0,0,0,0,0,10,0,0,0,0
Tonga (TGA),8,0,0,0,0,0,0,0,0,0,9,0,0,0,0
Trinidad and Tobago (TRI) [TRI],16,2,5,11,18,3,0,0,0,0,19,2,5,11,18
Tunisia (TUN),13,3,3,4,10,0,0,0,0,0,13,3,3,4,10
Turkey (TUR),21,39,25,24,88,16,0,0,0,0,37,39,25,24,88
Uganda (UGA),14,2,3,2,7,0,0,0,0,0,14,2,3,2,7
Ukraine (UKR),5,33,27,55,115,6,2,0,4,7,11,35,28,59,122
United Arab Emirates (UAE),8,0,0,0,0,0,0,0,0,0,8,0,0,0,0
United States (USA) [P] [Q] [R] [Z],26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681
Uruguay (URU),20,2,2,6,10,0,0,0,0,0,21,2,2,6,10
Uzbekistan (UZB),5,5,5,10,20,6,0,0,0,0,11,6,5,10,21
Venezuela (VEN),17,2,2,8,12,4,0,0,0,0,21,2,2,8,12
Vietnam (VIE),14,0,2,0,2,0,0,0,0,0,14,0,2,0,2
Virgin Islands (ISV),11,0,0,0,0,7,0,0,0,0,18,0,0,0,0
Yugoslavia (YUG) [YUG],16,26,29,28,83,14,0,3,0,4,30,26,32,29,87
Independent Olympic Participants (IOP) [IOP],0,0,0,2,3,0,0,0,0,0,0,0,0,2,3
Zambia (ZAM) [ZAM],12,0,0,0,2,0,0,0,0,0,12,0,0,0,2
Zimbabwe (ZIM) [ZIM],12,3,4,0,8,0,0,0,0,0,13,3,4,0,8
Mixed team (ZZX) [ZZX],3,8,5,4,17,0,0,0,0,0,3,8,5,4,17
Totals,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579

In [1]:
l=[]
sum(l)

0

# Probability and Statistics:
* Probability is a study of random events
* Probably - unlikely 

* statistics  - Group, data samples(uniform) / subset of population
    * Descriptive (Describe data set / visualizations / summary) :
        * central tendancy - mean/ median 
        * measures of dispersion - range , stadardndeviation, variance etc
    * Inferential statistics (Conclusion / Prediction / To Generalize the data):
        * 
### Statistical Analysis
* Desciptive:

    * Data Collection : Collecting Data from Population
    * Desciptive statistics : summarizing data, visualization data
*
    * Exploratory data analysis - EDA : patterns, differences , identity limitations
    * Estimation : estimate characteristics
    * Hypothesis testing : 
* Raw Data : directly take value
* Recode : calculated from raw data like (Total in olympics)


sample size = frequency/total number pof samples

In [4]:
m=[23,34,54]
mean = sum(m)/len(m)
mean

37.0

In [8]:
import  numpy as np
n=np.array(m)
n.mean()

37.0

In [11]:
sumSigma =0
for i in m:
    sumSigma += (i - mean)**2
variance = sumSigma / len(m)
stdDeviation = variance ** 0.5
stdDeviation

12.832251036613439

In [41]:
from collections import Counter 
marks = [100,1,1,2,1,2,100,23]
di=Counter(marks)
di=dict(di)
di

{100: 2, 1: 3, 2: 2, 23: 1}

In [43]:
for k,v in di.items():
    if v == max(di.values()):
        print(k)

1

In [38]:
max(di.values())

2

In [ ]:
values to frequency is probability
probability to values PMF Probability

In [26]:
d=sorted(marks)
d

[1, 1, 2, 2, 23, 100, 100]

In [30]:
median = d[len(d)//2]
median
d

[1, 1, 2, 2, 23, 100, 100]

In [12]:
l=[2,3,4]
l1=[3,7,4,5]
l+l1

[2, 3, 4, 3, 7, 4, 5]

In [10]:
l.extend(l1)
l

[2, 3, 4, 3, 7, 4, 5, 3, 7, 4, 5, 3, 7, 4, 5]

In [13]:
dir(())

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'count',
 'index']

In [34]:

l2=[9,3,1,7,2,8,4,7]
l2

[9, 3, 1, 7, 2, 8, 4, 7]

In [30]:

l2=sorted(l2[:len(l2)//2])+sorted(l2[len(l2)//2:],reverse=True)
l2

[1, 3, 7, 9, 8, 7, 4, 2]

In [35]:

l2=sorted(l2[:4])+sorted(l2[4:],reverse=True)
l2

[1, 3, 7, 9, 8, 7, 4, 2]

In [48]:
def fun():
                                                                       print("dnmfb")
                                                                       print("dfjkdshf")
fun()

dnmfb
dfjkdshf

In [50]:
# Positional Arguments

def std(id,name,mark):
    print(id,name,mark)
std(12,"mercy",234)

12 mercy 234

In [146]:
def teacher(t):
    print(t)

def std(id,name,mark): # marks = 60  defalut arguments
    print(id,name,mark)
    return id
#std(12,"mercy",234)
t=std(12,"m3e",23)
teacher(t)

12 m3e 23
12

In [59]:
def teacher(t):
    print(t)

def std(id=3,name,mark): # syntax error== After completing non_defalut arguments then give default arguments
    print(id,name,mark)
    return id
#std(12,"mercy",234)
t=std(12,"m3e",23)
teacher(t)

SyntaxError: non-default argument follows default argument (<ipython-input-59-30964b08deb0>, line 4)

In [72]:
# Use local variables as global 
id=6
def student(name):
    global id
    id =4
    print(id,name)
    
print(id)
student("fd")
print(id)

6
4 fd
4

In [86]:
# 
def std():
    id=2
    name = "dnfm"

    marks = 34
    
    def teacher():
        nonlocal marks
        marks=24
    teacher()
    print(marks)
    
std()
#print(marks)

24

In [92]:
# variable length arguments

def add(a,b):
    c=a + b
    return c
add(2,4)

6

In [95]:
def add(a,*b):
    c=a + sum(b)
    return c
add(2,4,4,5,6)

21

In [99]:
def add(a,*b):  # always gives * to last arguments
    sum=0
    for i in b:
        sum+=i
    return sum+a
add(2,4,4,5,6)

21

In [104]:
# keyword arguments **kwargs

def add1(**n):
    sum=0
    for i in n.values():
        sum+=int(i)
        
    return sum

add1(a=1,b=3,c=6)

10

In [105]:
def add1(**n):
    for k,v in n.items():
        print(k,v)

add1(name="Mercy",num=447)

name Mercy
num 447

In [110]:
import keyword
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [ ]:
# Local server
# Staging server
# Production server

In [142]:
try:
    c=0
    a = input("enter a value")
#     a ="1"
    b = 5
    c = a+b   # here a is str and b is int so type error
    print(c)
except TypeError: 
    a = int(input("enter value"))
    b=45
    c=a+b
    print(c)
else:
    print("all okay")           
    
finally:
    a = 5
    b = 6
    c=a+b
    print(c)    # if try and except not work then directly go to finally block

enter a value4
enter value5
50
11

In [143]:
try:
    c=0
    a = input("enter a value")
#     a ="1"
    b = "5"
    c = a+b   # here a is str and b is int so type error
    print(c)
except TypeError: 
    a = int(input("enter value"))    
    b=45
    c=a+b
    print(c)
else:                             # if try work except not work then execute else block 
    print("all okay")
    
finally:
    a = 5
    b = 6
    c=a+b
    print(c)

enter a value3
35
all okay
11

In [144]:
sum=0
while 1:
    try:
        n = int(input())
        sum+=n
    except:
        break
    
    
print(sum)

3
4
5
6

18

In [149]:
n="4"
n+5

TypeError: can only concatenate str (not "int") to str

In [150]:
10/0

ZeroDivisionError: division by zero

In [ ]:
^[9876]{1}[0-9]{9}$   for Phone validation

In [153]:
import collections
help(collections)

Help on package collections:

NAME
    collections

DESCRIPTION
    This module implements specialized container datatypes providing
    alternatives to Python's general purpose built-in containers, dict,
    list, set, and tuple.

    * namedtuple   factory function for creating tuple subclasses with named fields
    * deque        list-like container with fast appends and pops on either end
    * ChainMap     dict-like class for creating a single view of multiple mappings
    * Counter      dict subclass for counting hashable objects
    * OrderedDict  dict subclass that remembers the order entries were added
    * defaultdict  dict subclass that calls a factory function to supply missing values
    * UserDict     wrapper around dictionary objects for easier dict subclassing
    * UserList     wrapper around list objects for easier list subclassing
    * UserString   wrapper around string objects for easier string subclassing

PACKAGE CONTENTS
    abc

SUBMODULES
    _collections_abc

CLASSES
    builtins.dict(builtins.object)
        Counter
        OrderedDict
        defaultdict
    builtins.object
        deque
    collections.abc.MutableMapping(collections.abc.Mapping)
        ChainMap
        UserDict
    collections.abc.MutableSequence(collections.abc.Sequence)
        UserList
    collections.abc.Sequence(collections.abc.Reversible, collections.abc.Collection)
        UserString

    class ChainMap(collections.abc.MutableMapping)
     |  ChainMap(*maps)
     |
     |  A ChainMap groups multiple dicts (or other mappings) together
     |  to create a single, updateable view.
     |
     |  The underlying mappings are stored in a list.  That list is public and can
     |  be accessed or updated using the *maps* attribute.  There is no other
     |  state.
     |
     |  Lookups search the underlying mappings successively until a key is found.
     |  In contrast, writes, updates, and deletions only operate on the first
     |  mapping.
     |
     |  Method resolution order:
     |      ChainMap
     |      collections.abc.MutableMapping
     |      collections.abc.Mapping
     |      collections.abc.Collection
     |      collections.abc.Sized
     |      collections.abc.Iterable
     |      collections.abc.Container
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __bool__(self)
     |
     |  __contains__(self, key)
     |
     |  __copy__ = copy(self)
     |
     |  __delitem__(self, key)
     |
     |  __getitem__(self, key)
     |
     |  __init__(self, *maps)
     |      Initialize a ChainMap by setting *maps* to the given mappings.
     |      If no mappings are provided, a single empty dictionary is used.
     |
     |  __iter__(self)
     |
     |  __len__(self)
     |
     |  __missing__(self, key)
     |
     |  __repr__(self)
     |      Return repr(self).
     |
     |  __setitem__(self, key, value)
     |
     |  clear(self)
     |      Clear maps[0], leaving maps[1:] intact.
     |
     |  copy(self)
     |      New ChainMap or subclass with a new copy of maps[0] and refs to maps[1:]
     |
     |  get(self, key, default=None)
     |      D.get(k[,d]) -> D[k] if k in D, else d.  d defaults to None.
     |
     |  new_child(self, m=None)
     |      New ChainMap with a new map followed by all previous maps.
     |      If no map is provided, an empty dict is used.
     |
     |  pop(self, key, *args)
     |      Remove *key* from maps[0] and return its value. Raise KeyError if *key* not in maps[0].
     |
     |  popitem(self)
     |      Remove and return an item pair from maps[0]. Raise KeyError is maps[0] is empty.
     |
     |  ----------------------------------------------------------------------
     |  Class methods defined here:
     |
     |  fromkeys(iterable, *args) from abc.ABCMeta
     |      Create a ChainMap with a single dict created from the iterable.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  parents
     |      New ChainMap from maps[1:].
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes defined here:
     |
     |  __abstractmethods__ = frozenset()
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from collections.abc.MutableMapping:
     |
     |  setdefault(self, key, default=None)
     |      D.setdefault(k[,d]) -> D.get(k,d), also set D[k]=d if k not in D
     |
     |  update(*args, **kwds)
     |      D.update([E, ]**F) -> None.  Update D from mapping/iterable E and F.
     |      If E present and has a .keys() method, does:     for k in E: D[k] = E[k]
     |      If E present and lacks .keys() method, does:     for (k, v) in E: D[k] = v
     |      In either case, this is followed by: for k, v in F.items(): D[k] = v
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from collections.abc.Mapping:
     |
     |  __eq__(self, other)
     |      Return self==value.
     |
     |  items(self)
     |      D.items() -> a set-like object providing a view on D's items
     |
     |  keys(self)
     |      D.keys() -> a set-like object providing a view on D's keys
     |
     |  values(self)
     |      D.values() -> an object providing a view on D's values
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from collections.abc.Mapping:
     |
     |  __hash__ = None
     |
     |  __reversed__ = None
     |
     |  ----------------------------------------------------------------------
     |  Class methods inherited from collections.abc.Collection:
     |
     |  __subclasshook__(C) from abc.ABCMeta
     |      Abstract classes can override this to customize issubclass().
     |
     |      This is invoked early on by abc.ABCMeta.__subclasscheck__().
     |      It should return True, False or NotImplemented.  If it returns
     |      NotImplemented, the normal algorithm is used.  Otherwise, it
     |      overrides the normal algorithm (and the outcome is cached).

    class Counter(builtins.dict)
     |  Counter(*args, **kwds)
     |
     |  Dict subclass for counting hashable items.  Sometimes called a bag
     |  or multiset.  Elements are stored as dictionary keys and their counts
     |  are stored as dictionary values.
     |
     |  >>> c = Counter('abcdeabcdabcaba')  # count elements from a string
     |
     |  >>> c.most_common(3)                # three most common elements
     |  [('a', 5), ('b', 4), ('c', 3)]
     |  >>> sorted(c)                       # list all unique elements
     |  ['a', 'b', 'c', 'd', 'e']
     |  >>> ''.join(sorted(c.elements()))   # list elements with repetitions
     |  'aaaaabbbbcccdde'
     |  >>> sum(c.values())                 # total of all counts
     |  15
     |
     |  >>> c['a']                          # count of letter 'a'
     |  5
     |  >>> for elem in 'shazam':           # update counts from an iterable
     |  ...     c[elem] += 1                # by adding 1 to each element's count
     |  >>> c['a']                          # now there are seven 'a'
     |  7
     |  >>> del c['b']                      # remove all 'b'
     |  >>> c['b']                          # now there are zero 'b'
     |  0
     |
     |  >>> d = Counter('simsalabim')       # make another counter
     |  >>> c.update(d)                     # add in the second counter
     |  >>> c['a']                          # now there are nine 'a'
     |  9
     |
     |  >>> c.clear()                       # empty the counter
     |  >>> c
     |  Counter()
     |
     |  Note:  If a count is set to zero or reduced to zero, it will remain
     |  in the counter until the entry is deleted or the counter is cleared:
     |
     |  >>> c = Counter('aaabbc')
     |  >>> c['b'] -= 2                     # reduce the count of 'b' by two
     |  >>> c.most_common()                 # 'b' is still in, but its count is zero
     |  [('a', 3), ('c', 1), ('b', 0)]
     |
     |  Method resolution order:
     |      Counter
     |      builtins.dict
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __add__(self, other)
     |      Add counts from two counters.
     |
     |      >>> Counter('abbb') + Counter('bcc')
     |      Counter({'b': 4, 'c': 2, 'a': 1})
     |
     |  __and__(self, other)
     |      Intersection is the minimum of corresponding counts.
     |
     |      >>> Counter('abbb') & Counter('bcc')
     |      Counter({'b': 1})
     |
     |  __delitem__(self, elem)
     |      Like dict.__delitem__() but does not raise KeyError for missing values.
     |
     |  __iadd__(self, other)
     |      Inplace add from another counter, keeping only positive counts.
     |
     |      >>> c = Counter('abbb')
     |      >>> c += Counter('bcc')
     |      >>> c
     |      Counter({'b': 4, 'c': 2, 'a': 1})
     |
     |  __iand__(self, other)
     |      Inplace intersection is the minimum of corresponding counts.
     |
     |      >>> c = Counter('abbb')
     |      >>> c &= Counter('bcc')
     |      >>> c
     |      Counter({'b': 1})
     |
     |  __init__(*args, **kwds)
     |      Create a new, empty Counter object.  And if given, count elements
     |      from an input iterable.  Or, initialize the count from another mapping
     |      of elements to their counts.
     |
     |      >>> c = Counter()                           # a new, empty counter
     |      >>> c = Counter('gallahad')                 # a new counter from an iterable
     |      >>> c = Counter({'a': 4, 'b': 2})           # a new counter from a mapping
     |      >>> c = Counter(a=4, b=2)                   # a new counter from keyword args
     |
     |  __ior__(self, other)
     |      Inplace union is the maximum of value from either counter.
     |
     |      >>> c = Counter('abbb')
     |      >>> c |= Counter('bcc')
     |      >>> c
     |      Counter({'b': 3, 'c': 2, 'a': 1})
     |
     |  __isub__(self, other)
     |      Inplace subtract counter, but keep only results with positive counts.
     |
     |      >>> c = Counter('abbbc')
     |      >>> c -= Counter('bccd')
     |      >>> c
     |      Counter({'b': 2, 'a': 1})
     |
     |  __missing__(self, key)
     |      The count of elements not in the Counter is zero.
     |
     |  __neg__(self)
     |      Subtracts from an empty counter.  Strips positive and zero counts,
     |      and flips the sign on negative counts.
     |
     |  __or__(self, other)
     |      Union is the maximum of value in either of the input counters.
     |
     |      >>> Counter('abbb') | Counter('bcc')
     |      Counter({'b': 3, 'c': 2, 'a': 1})
     |
     |  __pos__(self)
     |      Adds an empty counter, effectively stripping negative and zero counts
     |
     |  __reduce__(self)
     |      Helper for pickle.
     |
     |  __repr__(self)
     |      Return repr(self).
     |
     |  __sub__(self, other)
     |      Subtract count, but keep only results with positive counts.
     |
     |      >>> Counter('abbbc') - Counter('bccd')
     |      Counter({'b': 2, 'a': 1})
     |
     |  copy(self)
     |      Return a shallow copy.
     |
     |  elements(self)
     |      Iterator over elements repeating each as many times as its count.
     |
     |      >>> c = Counter('ABCABC')
     |      >>> sorted(c.elements())
     |      ['A', 'A', 'B', 'B', 'C', 'C']
     |
     |      # Knuth's example for prime factors of 1836:  2**2 * 3**3 * 17**1
     |      >>> prime_factors = Counter({2: 2, 3: 3, 17: 1})
     |      >>> product = 1
     |      >>> for factor in prime_factors.elements():     # loop over factors
     |      ...     product *= factor                       # and multiply them
     |      >>> product
     |      1836
     |
     |      Note, if an element's count has been set to zero or is a negative
     |      number, elements() will ignore it.
     |
     |  most_common(self, n=None)
     |      List the n most common elements and their counts from the most
     |      common to the least.  If n is None, then list all element counts.
     |
     |      >>> Counter('abcdeabcdabcaba').most_common(3)
     |      [('a', 5), ('b', 4), ('c', 3)]
     |
     |  subtract(*args, **kwds)
     |      Like dict.update() but subtracts counts instead of replacing them.
     |      Counts can be reduced below zero.  Both the inputs and outputs are
     |      allowed to contain zero and negative counts.
     |
     |      Source can be an iterable, a dictionary, or another Counter instance.
     |
     |      >>> c = Counter('which')
     |      >>> c.subtract('witch')             # subtract elements from another iterable
     |      >>> c.subtract(Counter('watch'))    # subtract elements from another counter
     |      >>> c['h']                          # 2 in which, minus 1 in witch, minus 1 in watch
     |      0
     |      >>> c['w']                          # 1 in which, minus 1 in witch, minus 1 in watch
     |      -1
     |
     |  update(*args, **kwds)
     |      Like dict.update() but add counts instead of replacing them.
     |
     |      Source can be an iterable, a dictionary, or another Counter instance.
     |
     |      >>> c = Counter('which')
     |      >>> c.update('witch')           # add elements from another iterable
     |      >>> d = Counter('watch')
     |      >>> c.update(d)                 # add elements from another counter
     |      >>> c['h']                      # four 'h' in which, witch, and watch
     |      4
     |
     |  ----------------------------------------------------------------------
     |  Class methods defined here:
     |
     |  fromkeys(iterable, v=None) from builtins.type
     |      Create a new dictionary with keys from iterable and values set to value.
     |
     |  ----------------------------------------------------------------------
     |  Data descriptors defined here:
     |
     |  __dict__
     |      dictionary for instance variables (if defined)
     |
     |  __weakref__
     |      list of weak references to the object (if defined)
     |
     |  ----------------------------------------------------------------------
     |  Methods inherited from builtins.dict:
     |
     |  __contains__(self, key, /)
     |      True if the dictionary has the specified key, else False.
     |
     |  __eq__(self, value, /)
     |      Return self==value.
     |
     |  __ge__(self, value, /)
     |      Return self>=value.
     |
     |  __getattribute__(self, name, /)
     |      Return getattr(self, name).
     |
     |  __getitem__(...)
     |      x.__getitem__(y) <==> x[y]
     |
     |  __gt__(self, value, /)
     |      Return self>value.
     |
     |  __iter__(self, /)
     |      Implement iter(self).
     |
     |  __le__(self, value, /)
     |      Return self<=value.
     |
     |  __len__(self, /)
     |      Return len(self).
     |
     |  __lt__(self, value, /)
     |      Return self<value.
     |
     |  __ne__(self, value, /)
     |      Return self!=value.
     |
     |  __setitem__(self, key, value, /)
     |      Set self[key] to value.
     |
     |  __sizeof__(...)
     |      D.__sizeof__() -> size of D in memory, in bytes
     |
     |  clear(...)
     |      D.clear() -> None.  Remove all items from D.
     |
     |  get(self, key, default=None, /)
     |      Return the value for key if key is in the dictionary, else default.
     |
     |  items(...)
     |      D.items() -> a set-like object providing a view on D's items
     |
     |  keys(...)
     |      D.keys() -> a set-like object providing a view on D's keys
     |
     |  pop(...)
     |      D.pop(k[,d]) -> v, remove specified key and return the corresponding value.
     |      If key is not found, d is returned if given, otherwise KeyError is raised
     |
     |  popitem(...)
     |      D.popitem() -> (k, v), remove and return some (key, value) pair as a
     |      2-tuple; but raise KeyError if D is empty.
     |
     |  setdefault(self, key, default=None, /)
     |      Insert key with a value of default if key is not in the dictionary.
     |
     |      Return the value for key if key is in the dictionary, else default.
     |
     |  values(...)
     |      D.values() -> an object providing a view on D's values
     |
     |  ----------------------------------------------------------------------
     |  Static methods inherited from builtins.dict:
     |
     |  __new__(*args, **kwargs) from builtins.type
     |      Create and return a new object.  See help(type) for accurate signature.
     |
     |  ----------------------------------------------------------------------
     |  Data and other attributes inherited from builtins.dict:
     |
     |  __hash__ = None

    class OrderedDict(builtins.dict)
     |  Dictionary that remembers insertion order
     |
     |  Method resolution order:
     |      OrderedDict
     |      builtins.dict
     |      builtins.object
     |
     |  Methods defined here:
     |
     |  __delitem__(self, key, /)
     |      Delete self[key].
     |
     |  __eq__(self, value, /)
     |      Return self==value.
     |
     |  __ge__(self, value, /)
     |      Return self>=value.
     |
     |  __gt__(self, value, /)
     |      Return self>value.
     |
     |  __init__(self, /, *args, **kwargs)
     |      Initialize self.  See help(type(self)) for accurate signature.
     |
     |  __iter__(self, /)
     |      Implement iter(self).
     |
     |  __le__(self, value, /)
     |      Return self<=value.
     |
     |  __lt__(self, value, /)
     |      Return self<value.
     |
     |  __ne__(self, value, /)
     |      Return self!=value.
     |
     |  __reduce__(...)
     |      Return state information for pickling
     |
     |  __repr__(self, /)
     |      Return repr(self).
     |
     |  __reversed__(...)
     |      od.__reversed__() <==> reversed(od)
     |
     |  __setitem__(self, key, value, /)
     |      Set self[key] to value.
     |
     |  __sizeof__(...)
     |      D.__sizeof__() -> size of D in memory, in bytes
     |
     |  clear(...)
     |      od.clear() -> None.  Remove all items from od.
     |
     |  copy(...)
     |      od.copy() -> a shallow copy of od
     |
     |  items(...)
     |      D.items() -> a set-like object providing a view on D's items
     |
     |  keys(...)
     |      D.keys() -> a set-like object providing a view on D's keys
     |
     |  move_to_end(self, /, key, last=True)
     |      Move an existing element to the end (or beginning if last is false).
     |
     |      Raise KeyError if the element does not exist.
     |
     |  pop(...)
     |      od.pop(k[,d]) -> v, remove specified key and return the corresponding
     |      value.  If key is not found, d is returned if given, otherwise KeyError
     |      is raised.
     |
     |  popitem(self, /, last=True)
     |      Remove and return a (key, value) pair from the dictionary.
     |
     |      Pairs are returned in LIFO order if last is true or FIFO order if false.
     |
     |  setdefault(self, /, key, default=None)
     |      Insert key with a value of default if key is not in the dictionary.
     |
     |      Return the value for key if key is in the dictionary, else default.
     |
     |  update(...)
     |      D.update([E, ]**F) -> None.  Update D from dict/iterable E and F.
     |      If E is present and has a .keys() method, then does:  for k in E: D[k] = E[k]
     |      If E is present and lacks a .keys() method, then does:  for k, v in E: D[k] = v

In [18]:
import datetime 
d=datetime.datetime.now()
d

datetime.datetime(2019, 11, 21, 9, 54, 40, 404281)

In [11]:
d.day

21

In [16]:
d.month

11

In [12]:
d.year

2019

In [13]:
d.hour

9

In [14]:
d.second

14

In [15]:
d.microsecond

964624

In [23]:
import calendar as c
dir(calendar)

['Calendar',
 'EPOCH',
 'FRIDAY',
 'February',
 'HTMLCalendar',
 'IllegalMonthError',
 'IllegalWeekdayError',
 'January',
 'LocaleHTMLCalendar',
 'LocaleTextCalendar',
 'MONDAY',
 'SATURDAY',
 'SUNDAY',
 'THURSDAY',
 'TUESDAY',
 'TextCalendar',
 'WEDNESDAY',
 '_EPOCH_ORD',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_colwidth',
 '_locale',
 '_localized_day',
 '_localized_month',
 '_spacing',
 'c',
 'calendar',
 'datetime',
 'day_abbr',
 'day_name',
 'different_locale',
 'error',
 'firstweekday',
 'format',
 'formatstring',
 'isleap',
 'leapdays',
 'main',
 'mdays',
 'month',
 'month_abbr',
 'month_name',
 'monthcalendar',
 'monthlen',
 'monthrange',
 'nextmonth',
 'prcal',
 'prevmonth',
 'prmonth',
 'prweek',
 'repeat',
 'setfirstweekday',
 'sys',
 'timegm',
 'week',
 'weekday',
 'weekheader']

In [25]:
print(c.month(2019,11))

   November 2019
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30

In [26]:
print(c.month(2020,11))

   November 2020
Mo Tu We Th Fr Sa Su
                   1
 2  3  4  5  6  7  8
 9 10 11 12 13 14 15
16 17 18 19 20 21 22
23 24 25 26 27 28 29
30

In [27]:
c.isleap(2020)

True

In [28]:
c.monthrange(2019,11) # 4weeks 30days in 11-2019

(4, 30)

In [29]:
c.weekday(2019,11,22) # 4 is for friday 0-6 mon to sun

4

In [33]:
print(c.leapdays(2000,2020))

5

In [47]:
import time as t
dir(time)

['_STRUCT_TM_ITEMS',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'altzone',
 'asctime',
 'clock',
 'ctime',
 'daylight',
 'get_clock_info',
 'gmtime',
 'localtime',
 'mktime',
 'monotonic',
 'monotonic_ns',
 'perf_counter',
 'perf_counter_ns',
 'process_time',
 'process_time_ns',
 'sleep',
 'strftime',
 'strptime',
 'struct_time',
 'thread_time',
 'thread_time_ns',
 'time',
 'time_ns',
 'timezone',
 'tzname']

In [50]:
t.localtime(time.time())

time.struct_time(tm_year=2019, tm_mon=11, tm_mday=21, tm_hour=10, tm_min=29, tm_sec=48, tm_wday=3, tm_yday=325, tm_isdst=0)

In [56]:
from datetime import date
today=date.today()
today

datetime.date(2019, 11, 21)

In [59]:
d2=today.strftime("%d %B %y")
d2

'21 November 19'

In [60]:
d3=today.strftime("%d %m %y")
d3

'21 11 19'

In [62]:
calendar.prcal(2020)

                                  2020

      January                   February                   March
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2                         1
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       2  3  4  5  6  7  8
13 14 15 16 17 18 19      10 11 12 13 14 15 16       9 10 11 12 13 14 15
20 21 22 23 24 25 26      17 18 19 20 21 22 23      16 17 18 19 20 21 22
27 28 29 30 31            24 25 26 27 28 29         23 24 25 26 27 28 29
                                                    30 31

       April                      May                       June
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                   1  2  3       1  2  3  4  5  6  7
 6  7  8  9 10 11 12       4  5  6  7  8  9 10       8  9 10 11 12 13 14
13 14 15 16 17 18 19      11 12 13 14 15 16 17      15 16 17 18 19 20 21
20 21 22 23 24 25 26      18 19 20 21 22 23 24      22 23 24 25 26 27 28
27 28 29 30               25 26 27 28 29 30 31      29 30

        July                     August                  September
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
       1  2  3  4  5                      1  2          1  2  3  4  5  6
 6  7  8  9 10 11 12       3  4  5  6  7  8  9       7  8  9 10 11 12 13
13 14 15 16 17 18 19      10 11 12 13 14 15 16      14 15 16 17 18 19 20
20 21 22 23 24 25 26      17 18 19 20 21 22 23      21 22 23 24 25 26 27
27 28 29 30 31            24 25 26 27 28 29 30      28 29 30
                          31

      October                   November                  December
Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su      Mo Tu We Th Fr Sa Su
          1  2  3  4                         1          1  2  3  4  5  6
 5  6  7  8  9 10 11       2  3  4  5  6  7  8       7  8  9 10 11 12 13
12 13 14 15 16 17 18       9 10 11 12 13 14 15      14 15 16 17 18 19 20
19 20 21 22 23 24 25      16 17 18 19 20 21 22      21 22 23 24 25 26 27
26 27 28 29 30 31         23 24 25 26 27 28 29      28 29 30 31
                          30

In [64]:
type(-4)

int

In [2]:
from tkinter  import *
tk = Tk()
canvas = Canvas(tk,width=400,height=400)
canvas.pack()
canvas.create_arc(10,10,200,100,extent=180)
tk.mainloop()

In [3]:
import turtle
t=turtle.Pen()
t.color(1,0,0)
t.begin_fill()
t.forward(100)
t.left(90)

In [5]:
tk = Tk()
btn =Button(tk, text="click me")
btn.pack()

# Numpy

In [42]:
import numpy as np
d=np.random.rand(3,3)
d

array([[0.99199513, 0.70116868, 0.9279274 ],
       [0.38329563, 0.32965956, 0.0287424 ],
       [0.07210772, 0.54139269, 0.3194757 ]])

In [43]:
import numpy as np
dd=np.random.randn(3,3)
d=d*10
dd

array([[ 0.56504854, -2.55292243, -0.32417476],
       [-0.64846276, -0.44657799,  0.44493228],
       [ 0.8849277 ,  1.1187518 ,  0.0744    ]])

In [45]:
import numpy as np
dd=np.random.randint(100)

dd

62

In [50]:
import numpy as np
dd=np.random.random(100)
dd

array([0.35710644, 0.6792544 , 0.86414418, 0.64580959, 0.37249421,
       0.97476108, 0.45265745, 0.51589719, 0.6508523 , 0.18987677,
       0.7205098 , 0.8061793 , 0.56133122, 0.68934661, 0.39167294,
       0.24020215, 0.92906762, 0.82634281, 0.18734524, 0.24858391,
       0.40077445, 0.49722896, 0.35909519, 0.97379135, 0.56600354,
       0.83795675, 0.21720707, 0.08812999, 0.67387282, 0.29601632,
       0.82385794, 0.89402569, 0.70215095, 0.69902627, 0.71170064,
       0.14582416, 0.76033434, 0.799305  , 0.95770369, 0.78583666,
       0.51039128, 0.28379786, 0.81428184, 0.37262838, 0.96835587,
       0.57552359, 0.85005404, 0.07227009, 0.40399377, 0.3387346 ,
       0.06923606, 0.6818639 , 0.0619089 , 0.38009138, 0.2845643 ,
       0.12387697, 0.44865937, 0.74071887, 0.09250193, 0.19846318,
       0.65585819, 0.26704219, 0.78445812, 0.35151055, 0.19699878,
       0.38604249, 0.2866345 , 0.73466817, 0.17775917, 0.02508639,
       0.02678714, 0.14117749, 0.30285289, 0.267543  , 0.31709073,
       0.34986843, 0.97822634, 0.49828162, 0.08923197, 0.61208577,
       0.489776  , 0.13939196, 0.1222313 , 0.13433311, 0.43911141,
       0.27637598, 0.81737544, 0.1177605 , 0.67331808, 0.78658388,
       0.71297683, 0.64788951, 0.5357179 , 0.09454371, 0.08259995,
       0.59460729, 0.17963289, 0.07299493, 0.4285645 , 0.85810506])

In [15]:
d+d

array([[15.6034183 , 18.2851963 , 13.89137981],
       [17.48799414,  3.11914698, 14.67928016],
       [12.75508591, 18.34047043,  8.51978124]])

In [19]:
f=np.array([[1,2,3],[4,5,6]])
f

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
f**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [21]:
1/f

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [22]:
f-f

array([[0, 0, 0],
       [0, 0, 0]])

In [51]:
f>2

array([[False, False,  True],
       [ True,  True,  True]])

In [60]:
arr=np.arange(10.5)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [55]:
arr[5:7]

array([5, 6])

In [56]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [64]:
arr[5:8]=12
arr

array([ 0.,  1.,  2.,  3.,  4., 12., 12., 12.,  8.,  9., 10.])

In [65]:
arr_s=arr[5:8]
arr_s

array([12., 12., 12.])

In [66]:
arr_s[1]=123
arr_s

array([ 12., 123.,  12.])

In [67]:
arr

array([  0.,   1.,   2.,   3.,   4.,  12., 123.,  12.,   8.,   9.,  10.])

In [76]:
array=np.array([[1,2,3],[4,5,6],[8,9,0]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [8, 9, 0]])

In [77]:
array.flatten("C") # Row wise concat and single dimention

array([1, 2, 3, 4, 5, 6, 8, 9, 0])

In [78]:
array.flatten("F")# column wise concat and single dimention

array([1, 4, 8, 2, 5, 9, 3, 6, 0])

In [83]:
g=np.arange(16).reshape(4,4)
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [84]:
g[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [94]:
g[1:4:2,1:4:2]

array([[ 5,  7],
       [13, 15]])

In [96]:
g[1:4:2,0:4:2]

array([[ 4,  6],
       [12, 14]])

In [105]:
arr1=np.arange(1,10).reshape(3,3)
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [106]:
arr1[1:2,1:]=0
arr1

array([[1, 2, 3],
       [4, 0, 0],
       [7, 8, 9]])

In [112]:
arr1[::-1,::-1]

array([[9, 8, 7],
       [0, 0, 4],
       [3, 2, 1]])

In [119]:
arr1[-1,-1]

9

In [122]:
arr1[1,2]

0

# Boolean Indexing

In [152]:
n=np.array(["a","b","a","e","e"])
data=np.random.rand(5,4)
print(n)
data

['a' 'b' 'a' 'e' 'e']

array([[0.38016002, 0.90537006, 0.96560618, 0.60841753],
       [0.47907458, 0.71174569, 0.98311242, 0.02082719],
       [0.61885318, 0.2266683 , 0.97540096, 0.13586258],
       [0.88090552, 0.28341345, 0.05331852, 0.6668619 ],
       [0.57686545, 0.37018013, 0.29823439, 0.38142444]])

In [128]:
n=="e"

array([False, False, False,  True,  True])

In [129]:
data[n=="e"]

array([[0.20977024, 0.49937676, 0.11546401, 0.91310624],
       [0.15089834, 0.08994733, 0.23109637, 0.50761597]])

In [130]:
data[n=="e",2:]

array([[0.11546401, 0.91310624],
       [0.23109637, 0.50761597]])

In [136]:
print(data[n=="a",3])
data[n=="a"]

[0.21939517 0.0084655 ]

array([[0.20212776, 0.50557916, 0.78450523, 0.21939517],
       [0.00430589, 0.97657828, 0.9490333 , 0.0084655 ]])

In [153]:
n=np.array([22,33,44,33,22])
data=np.random.randn(5,5)
print(n)
data

[22 33 44 33 22]

array([[ 0.18358878,  0.7791892 , -0.75577908,  0.7857629 ,  0.62867101],
       [ 0.29773914,  0.42713466,  1.22437917,  0.12069771, -0.11224172],
       [-0.67841114, -1.48209535,  0.06064821,  1.49305598,  1.2039119 ],
       [-0.41627509,  2.23694623,  1.18126343,  0.34458547, -0.51375516],
       [-0.28905738, -0.19432919,  1.86670128, -0.41364491, -0.26730832]])

In [140]:
data[n!=22]

array([[0.18433841, 0.72100162, 0.85494771, 0.45785697, 0.02244101],
       [0.75522939, 0.24961559, 0.89003618, 0.15594685, 0.39846611],
       [0.97996691, 0.16009477, 0.71878049, 0.06534875, 0.50586438]])

In [144]:
c=n==22
c

array([ True, False, False, False,  True])

In [147]:
data

array([[0.52409821, 0.74357673, 0.65710714, 0.58828799, 0.89706721],
       [0.18433841, 0.72100162, 0.85494771, 0.45785697, 0.02244101],
       [0.75522939, 0.24961559, 0.89003618, 0.15594685, 0.39846611],
       [0.97996691, 0.16009477, 0.71878049, 0.06534875, 0.50586438],
       [0.47764737, 0.32528627, 0.60454163, 0.89043881, 0.74528263]])

In [146]:
data[c]

array([[0.52409821, 0.74357673, 0.65710714, 0.58828799, 0.89706721],
       [0.47764737, 0.32528627, 0.60454163, 0.89043881, 0.74528263]])

In [145]:
data[~c]

array([[0.18433841, 0.72100162, 0.85494771, 0.45785697, 0.02244101],
       [0.75522939, 0.24961559, 0.89003618, 0.15594685, 0.39846611],
       [0.97996691, 0.16009477, 0.71878049, 0.06534875, 0.50586438]])

In [156]:
data[data<0]=0
data

array([[0.18358878, 0.7791892 , 0.        , 0.7857629 , 0.62867101],
       [0.29773914, 0.42713466, 1.22437917, 0.12069771, 0.        ],
       [0.        , 0.        , 0.06064821, 1.49305598, 1.2039119 ],
       [0.        , 2.23694623, 1.18126343, 0.34458547, 0.        ],
       [0.        , 0.        , 1.86670128, 0.        , 0.        ]])

In [159]:
data[(n==22 )| (n==33)]

array([[0.18358878, 0.7791892 , 0.        , 0.7857629 , 0.62867101],
       [0.29773914, 0.42713466, 1.22437917, 0.12069771, 0.        ],
       [0.        , 2.23694623, 1.18126343, 0.34458547, 0.        ],
       [0.        , 0.        , 1.86670128, 0.        , 0.        ]])

In [161]:
data[n!=22]=7
data

array([[0.18358878, 0.7791892 , 0.        , 0.7857629 , 0.62867101],
       [7.        , 7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 1.86670128, 0.        , 0.        ]])

In [167]:
ar=np.empty((8,4))
ar

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [175]:
for i in range(8):
    ar[i]=i
ar

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [187]:
ar[[4,3,0,6]][:,1:3] #4,3,0,6 rows

array([[4., 4.],
       [3., 3.],
       [0., 0.],
       [6., 6.]])

In [190]:
ar[[-3,-5,-4,-1]][:,[0,2,3]] # -3,-5,-4,-1 rows then 0,2,3 columns

array([[5., 5., 5.],
       [3., 3., 3.],
       [4., 4., 4.],
       [7., 7., 7.]])

In [191]:
ar[[1,3,2,3],[0,1,3,2]] # 1row ocloumn n 3row 1column

array([1., 3., 2., 3.])

In [195]:
print(ar)
print(ar.T)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
[[0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]
 [0. 1. 2. 3. 4. 5. 6. 7.]]

In [211]:
a=np.arange(16).reshape((2,2,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [219]:
print(a.transpose((1,0,2)))
print(a.transpose((2,0,1)))

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]
[[[ 0  4]
  [ 8 12]]

 [[ 1  5]
  [ 9 13]]

 [[ 2  6]
  [10 14]]

 [[ 3  7]
  [11 15]]]


        shape  original   Output1      Output2
       
matrix   2       0       2-4 matrix     1-2 matrix 
row      2       1       0-2 rows       0-2 rows
column   4       2       1-2 column     2-4 columns

# Pandas

In [2]:
import pandas as pd
obj=pd.Series([2,-2,23,5])
obj

0     2
1    -2
2    23
3     5
dtype: int64

In [3]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
obj.values

array([ 2, -2, 23,  5], dtype=int64)

In [9]:
import pandas as pd
obj2=pd.Series([2,-2,23,5],index=[1.1,2.2,3.3,4.4])
obj2

1.1     2
2.2    -2
3.3    23
4.4     5
dtype: int64

In [11]:
obj3=pd.Series([2,-2,23,5],index=["a","b","c","d"])
obj3

a     2
b    -2
c    23
d     5
dtype: int64

In [10]:
obj2[4.4]=0
obj2

1.1     2
2.2    -2
3.3    23
4.4     0
dtype: int64

In [12]:
obj3[obj3>2]

c    23
d     5
dtype: int64

In [13]:
obj2*2

1.1     4
2.2    -4
3.3    46
4.4     0
dtype: int64

In [15]:
obj2[4.4]=1
obj2

1.1     2
2.2    -2
3.3    23
4.4     1
dtype: int64

In [17]:
import numpy as np
np.exp(obj2)

1.1    7.389056e+00
2.2    1.353353e-01
3.3    9.744803e+09
4.4    2.718282e+00
dtype: float64

In [24]:
obj2[3.8]=5
obj2

1.1     2
2.2    -2
3.3    23
4.4     4
3.2     4
3.8     5
dtype: int64

In [25]:
2 in obj2

False

In [27]:
3.2 in obj2

True

In [28]:
dic={"chitti":95,"thotti":35,"potti":99}
ob=pd.Series(dic)
ob

chitti    95
thotti    35
potti     99
dtype: int64

In [30]:
st=["Merc","chitti","potti"]
obj=pd.Series(ob,index=st)
obj

Merc       NaN
chitti    95.0
potti     99.0
dtype: float64

In [34]:
pd.isnull(obj)
obj.isnull()

Merc       True
chitti    False
potti     False
dtype: bool

In [35]:
pd.notnull(obj)
obj.notnull()

Merc      False
chitti     True
potti      True
dtype: bool

In [37]:
obj+ob # if both are values present then only add else NaN

Merc        NaN
chitti    190.0
potti     198.0
thotti      NaN
dtype: float64